version: '3.3'
services:
  community:
    ports:
      - '8980:80'
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=Secret
      - 'OPENPROJECT_HOST__NAME=yourdomain.com'
      - OPENPROJECT_HTTPS=true
    restart: unless-stopped
    image: 'openproject/community:12'
    networks:
      - openproject


networks:
  openproject: